[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#d4d4d4'

[colors.cursor]
text = '#131313'
cursor = '#ffffff'

[colors.normal]
black   = '#131313'
red     = '#e14986'
green   = '#9dd66e'
yellow  = '#dba87b'
blue    = '#d05d5b'
magenta = '#bfbfbf'
cyan    = '#ffffff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f97'
green   = '#aee086'
yellow  = '#e8bd97'
blue    = '#d4d4d4'
magenta = '#bb5b6a'
cyan    = '#a9685e'
white   = '#ffffff'
